color0 #131317
color1 #ffb4ab
color2 #bbc3ff
color3 #c2c4e3
color4 #f1b2ed
color5 #bbc3ff
color6 #c2c4e3
color7 #e4e1e7
color8 #90909b
color9 #ffb4ab
color10 #bbc3ff
color11 #c2c4e3
color12 #f1b2ed
color13 #bbc3ff
color14 #c2c4e3
color15 #e4e1e7

cursor                #e4e1e7
cursor_text_color     #131317
background            #131317
foreground            #e4e1e7
selection_foreground  #c6c5d1
selection_background  #464650
active_border_color   #bbc3ff
inactive_border_color #464650
url_color             #bbc3ff

active_tab_foreground   #212b66
active_tab_background   #bbc3ff
inactive_tab_foreground #c6c5d1
inactive_tab_background #464650
cursor_trail_color      #c6c5d1
