# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x282828ff
rootcolor = 0x282828ff
bordercolor = 0x786f6bff
focuscolor = 0xebdbb2ff
maximizescreencolor = 0x8ec07cff
urgentcolor = 0xfb4934ff
scratchpadcolor = 0x83a598ff
globalcolor = 0xcc9b1fff
overlaycolor = 0x356722ff
